matrix:
    include:
        - os: osx
          language: objective-c
          python:
            - "3.5"
          sudo: required
          env:
            - TOXENV=py35
          install:
            - "PYTHONPATH=. pyinstaller --onefile pyportify.spec"
            - "hdiutil create dist/pyportify.dmg -srcfolder dist/ -ov"
          deploy:
          #  - provider: s3
          #    access_key_id:
          #      secure: "MYYo6qxwsOPiC7NDuDRyJB79Eo4QMsvDRokdD8uHoPcf9O5wTTKnqZDLZeeQhUzOrTcSuYCBdDR2Nxu+G0A9LLm2o8Hi+bTofNxl3GOXFIxHMo/Ra80cuweOmsQwpKpKT4ejm28f5cACWAL8qBebkPlBgM3Q6H/cC0aHB/patO4="
          #    secret_access_key:
          #      secure: "CV4xHW1+BvewQU6jQBiYikhxwuGkXrUxuL0gQQUV63WL1eD7lQVg8GE0b1mhUbtw047DHPgbrTQK5jaao/GBjO6ydXkJCyN+LncTzJhbekA7xWOdvjPlvNDOib2K8UKWyxlPCyuzZfKx9w+HRt5CWCBVwvTdmTGhx5KSpYWEpGQ="
          #    bucket: "pyportify"
          #    skip_cleanup: true
          #    acl: public_read
          #    local_dir: dist
            - provider: releases
              api_key:
                secure: SXoKAyll1TtFrQeOS5i65tzZLdZlXx5jEOnL3tlblmgcEn0sD4iILV/K/qv8KmeE8biBIdbtcqNJPh65covL8Yidaz211Hc4/MHhBU+rfqnrN0EcPR53/zmUgSbzWl7p62zvHdMSmS/iKQKT6Kv3pvyTEDL35oVX8lx0ckzcjkY
              skip_cleanup: true
              file: 'dist/pyportify.dmg'
              on:
                all_branches: true
                repo: rckclmbr/pyportify
                tags: true
            - provider: pypi
              user: jbraegger
              password:
                secure: P3dSxH4hgJ6JdnGc4zcCneM/jn2qczOh11uxFSJGHEvkMvL4vOrZ0yOiE8BBInUBeT/4kVfWNuBghibS1P06AlWWvUz66KHc719mpHBA3On+q/0troVXT1Pl9xiEr8ITvQda7wWgSZaxSVpaZnkMJZQQkR3ucc7p6qm4mygPyjs=
              on:
                all_branches: true
                repo: rckclmbr/pyportify
                tags: true
        - os: linux
          python: "3.4"
          env:
            - TOXENV=py34
          language: python
          sudo: required
          before_install:
            - "sudo apt-get update"
            - "sudo apt-get install python-all-dev pandoc"
            - "pip3 install tox"
            - "pandoc -f markdown -t rst -o README.rst README.md"
before_install:

  # Install python 3.5.0 on OS X
  # Workaround for Tavis's current lack of official support for Python on OS X
  # Reference https://github.com/travis-ci/travis-ci/issues/2312
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "TRAVIS_PYTHON_VERSION=$TRAVIS_PYTHON_VERSION";

      echo Updating Homebrew...;
      brew update;

      echo Installing pyenv...;
      brew unlink pyenv;
      brew install pyenv;

      echo Installing git...;
      brew unlink git;
      brew install git;

      echo Installing virtualenv...;
      brew unlink virtualenv;
      brew install virtualenv;

      echo Installing pyenv shims...;
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)";

      new_python_version="3.5.0";

      echo "Installing Python${new_python_version}...";
      env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install ${new_python_version};
      pyenv versions;

      echo "Making Python${new_python_version} the global python...";
      pyenv global ${new_python_version};

      echo "python --version" `python --version`;
      echo "pip --version" `pip --version`;

      echo Upgrading pip...;
      pip install --upgrade pip;

      echo Installing pandoc...;
      brew install pandoc;

      echo Installing package dependencies...;
      pip3 install pyinstaller==3.1.1 tox;
      pip3 install -r requirements.txt;
      pandoc -f markdown -t rst -o README.rst README.md;
    fi

script: tox
