language: python
python:
  - "3.5"
install:
  - "sudo apt-get update"
  - "sudo apt-get install python-all-dev pandoc"
  - "pandoc -f markdown -t rst -o README.rst README.md"
  - "pip install tox"
script: tox
deploy:
  provider: pypi
  user: jbraegger
  password:
    secure: P3dSxH4hgJ6JdnGc4zcCneM/jn2qczOh11uxFSJGHEvkMvL4vOrZ0yOiE8BBInUBeT/4kVfWNuBghibS1P06AlWWvUz66KHc719mpHBA3On+q/0troVXT1Pl9xiEr8ITvQda7wWgSZaxSVpaZnkMJZQQkR3ucc7p6qm4mygPyjs=
  on:
    all_branches: true
    repo: rckclmbr/pyportify
    tags: true
